# TCL File Generated by Component Editor 14.0
# Mon Nov 17 23:19:13 EST 2014
# DO NOT MODIFY


# 
# stream_to_avalon "stream_to_avalon" v1.0
#  2014.11.17.23:19:13
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module stream_to_avalon
# 
set_module_property DESCRIPTION ""
set_module_property NAME stream_to_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME stream_to_avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL stream_to_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file stream_to_avalon.vhd VHDL PATH stream_to_avalon.vhd TOP_LEVEL_FILE
add_fileset_file util.vhd VHDL PATH util.vhd
add_fileset_file fifos.vhdl VHDL PATH fifos.vhdl
add_fileset_file memory.vhdl VHDL PATH memory.vhdl
add_fileset_file sizing.vhdl VHDL PATH sizing.vhdl
add_fileset_file synchronizing.vhdl VHDL PATH synchronizing.vhdl
add_fileset_file TwoClockStreamFifo.vhdl VHDL PATH TwoClockStreamFifo.vhdl


# 
# parameters
# 
add_parameter STREAM_BW INTEGER 32
set_parameter_property STREAM_BW DEFAULT_VALUE 32
set_parameter_property STREAM_BW DISPLAY_NAME STREAM_BW
set_parameter_property STREAM_BW TYPE INTEGER
set_parameter_property STREAM_BW UNITS None
set_parameter_property STREAM_BW HDL_PARAMETER true


# 
# display items
# 


# 
# connection point ctl
# 
add_interface ctl avalon end
set_interface_property ctl addressUnits WORDS
set_interface_property ctl associatedClock avalon_clock
set_interface_property ctl associatedReset avalon_rst
set_interface_property ctl bitsPerSymbol 8
set_interface_property ctl burstOnBurstBoundariesOnly false
set_interface_property ctl burstcountUnits WORDS
set_interface_property ctl explicitAddressSpan 0
set_interface_property ctl holdTime 0
set_interface_property ctl linewrapBursts false
set_interface_property ctl maximumPendingReadTransactions 1
set_interface_property ctl maximumPendingWriteTransactions 0
set_interface_property ctl readLatency 0
set_interface_property ctl readWaitTime 1
set_interface_property ctl setupTime 0
set_interface_property ctl timingUnits Cycles
set_interface_property ctl writeWaitTime 0
set_interface_property ctl ENABLED true
set_interface_property ctl EXPORT_OF ""
set_interface_property ctl PORT_NAME_MAP ""
set_interface_property ctl CMSIS_SVD_VARIABLES ""
set_interface_property ctl SVD_ADDRESS_GROUP ""

add_interface_port ctl ctl_write write Input 1
add_interface_port ctl ctl_read read Input 1
add_interface_port ctl ctl_address address Input 4
add_interface_port ctl ctl_writedata writedata Input 32
add_interface_port ctl ctl_readdata readdata Output 32
add_interface_port ctl ctl_waitrequest waitrequest Output 1
add_interface_port ctl ctl_readdatavalid readdatavalid Output 1
set_interface_assignment ctl embeddedsw.configuration.isFlash 0
set_interface_assignment ctl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ctl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ctl embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_clock
# 
add_interface avalon_clock clock end
set_interface_property avalon_clock clockRate 0
set_interface_property avalon_clock ENABLED true
set_interface_property avalon_clock EXPORT_OF ""
set_interface_property avalon_clock PORT_NAME_MAP ""
set_interface_property avalon_clock CMSIS_SVD_VARIABLES ""
set_interface_property avalon_clock SVD_ADDRESS_GROUP ""

add_interface_port avalon_clock clk clk Input 1


# 
# connection point avalon_rst
# 
add_interface avalon_rst reset end
set_interface_property avalon_rst associatedClock avalon_clock
set_interface_property avalon_rst synchronousEdges BOTH
set_interface_property avalon_rst ENABLED true
set_interface_property avalon_rst EXPORT_OF ""
set_interface_property avalon_rst PORT_NAME_MAP ""
set_interface_property avalon_rst CMSIS_SVD_VARIABLES ""
set_interface_property avalon_rst SVD_ADDRESS_GROUP ""

add_interface_port avalon_rst rst reset Input 1


# 
# connection point stream_clk
# 
add_interface stream_clk clock end
set_interface_property stream_clk clockRate 0
set_interface_property stream_clk ENABLED true
set_interface_property stream_clk EXPORT_OF ""
set_interface_property stream_clk PORT_NAME_MAP ""
set_interface_property stream_clk CMSIS_SVD_VARIABLES ""
set_interface_property stream_clk SVD_ADDRESS_GROUP ""

add_interface_port stream_clk stream_clk clk Input 1


# 
# connection point in
# 
add_interface in avalon_streaming end
set_interface_property in associatedClock stream_clk
set_interface_property in associatedReset stream_rst
set_interface_property in dataBitsPerSymbol 8
set_interface_property in errorDescriptor ""
set_interface_property in firstSymbolInHighOrderBits true
set_interface_property in maxChannel 0
set_interface_property in readyLatency 0
set_interface_property in ENABLED true
set_interface_property in EXPORT_OF ""
set_interface_property in PORT_NAME_MAP ""
set_interface_property in CMSIS_SVD_VARIABLES ""
set_interface_property in SVD_ADDRESS_GROUP ""

add_interface_port in stream_data data Input stream_bw
add_interface_port in stream_valid valid Input 1
add_interface_port in stream_ready ready Output 1


# 
# connection point stream_rst
# 
add_interface stream_rst reset end
set_interface_property stream_rst associatedClock stream_clk
set_interface_property stream_rst synchronousEdges BOTH
set_interface_property stream_rst ENABLED true
set_interface_property stream_rst EXPORT_OF ""
set_interface_property stream_rst PORT_NAME_MAP ""
set_interface_property stream_rst CMSIS_SVD_VARIABLES ""
set_interface_property stream_rst SVD_ADDRESS_GROUP ""

add_interface_port stream_rst stream_rst reset Input 1


# 
# connection point mm
# 
add_interface mm avalon start
set_interface_property mm addressUnits SYMBOLS
set_interface_property mm associatedClock avalon_clock
set_interface_property mm associatedReset avalon_rst
set_interface_property mm bitsPerSymbol 8
set_interface_property mm burstOnBurstBoundariesOnly false
set_interface_property mm burstcountUnits WORDS
set_interface_property mm doStreamReads false
set_interface_property mm doStreamWrites false
set_interface_property mm holdTime 0
set_interface_property mm linewrapBursts false
set_interface_property mm maximumPendingReadTransactions 0
set_interface_property mm maximumPendingWriteTransactions 0
set_interface_property mm readLatency 0
set_interface_property mm readWaitTime 1
set_interface_property mm setupTime 0
set_interface_property mm timingUnits Cycles
set_interface_property mm writeWaitTime 0
set_interface_property mm ENABLED true
set_interface_property mm EXPORT_OF ""
set_interface_property mm PORT_NAME_MAP ""
set_interface_property mm CMSIS_SVD_VARIABLES ""
set_interface_property mm SVD_ADDRESS_GROUP ""

add_interface_port mm writer_write write Output 1
add_interface_port mm writer_waitrequest waitrequest Input 1
add_interface_port mm writer_address address Output 32
add_interface_port mm writer_burstcount burstcount Output 10
add_interface_port mm writer_writedata writedata Output 128

